name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  train_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t ./package

      - name: Train model
        run: |
          python model/train_model.py

      - name: Copy lambda function, model and trained model
        run: |
          cp lambda_function.py ./package/
          cp -r model ./package/
          cp trained_model.joblib ./package/

      - name: Zip deployment package
        run: |
          cd package
          zip -r ../deployment_package.zip .
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Lambda function
        uses: aws-actions/deploy-lambda-function@v1
        with:
          function-name: your-lambda-function-name
          zip-file: deployment_package.zip

      - name: Invoke Lambda function for testing
        run: |
          aws lambda invoke --function-name your-lambda-function-name --payload '{"media_objects": [{"type": "video", "width": 1920, "height": 1080, "duration": 60}]}' output.json
          cat output.json
